<?php

Route::group(['before' => 'verify.ssl'], function() {

	Route::get('/', ['as' => 'home', function() {
		$package = Package::first();

		return View::make('homepage.index', compact('package'));
	}]);

	Route::get('emailGet', ['as' => 'email.get', 'uses' => 'CheckoutController@emailGet']);
	Route::get('emailUpdate', ['as' => 'email.update', 'uses' => 'CheckoutController@emailUpdate']);
	Route::get('emailRollback', ['as' => 'email.rollback', 'uses' => 'CheckoutController@emailRollback']);
	
	// login and registration routes
	Route::get('login/{modal?}', ['before' => 'guest', 'as' => 'login', 'uses' => 'LoginController@login']);
	Route::get('register', ['before' => 'guest', 'as' => 'signup', 'uses' => 'LoginController@signup']);
	Route::post('login', ['before' => 'guest', 'as' => 'login', 'uses' => 'LoginController@processLogin']);
	Route::post('register', ['before' => 'guest', 'as' => 'signup', 'uses' => 'LoginController@processSignup']);
	Route::get('logout', ['before' => 'auth', 'as' => 'logout', 'uses' => 'LoginController@logout']);

	// password reset (automatically generated by laravel)
	Route::controller('password', 'RemindersController');

	// enroll and checkout routes
	Route::get('packages/{slug}/enroll', ['before' => 'auth', 'as' => 'packages.enroll', 'uses' => 'PackagesController@enroll']);
	Route::get('checkout', ['before' => 'auth', 'as' => 'cart', 'uses' => 'CheckoutController@cart']);
	Route::post('checkout', ['before' => 'auth|csrf', 'as' => 'cart.checkout', 'uses' => 'CheckoutController@checkout']);

	// user profile routes
	Route::group(['before' => 'auth|can_view_profile'], function() {
		Route::get('users/{username}', ['as' => 'profile', 'uses' => 'UsersController@profile']);
		Route::get('users/{username}/settings', ['as' => 'profile.settings', 'uses' => 'UsersController@settings']);
		Route::post('users/{username}/settings', ['as' => 'profile.settings', 'uses' => 'UsersController@saveSettings']);
		Route::get('users/{username}/billing', ['as' => 'profile.billing', 'uses' => 'UsersController@billing']);
		Route::get('users/{username}/billing/{payment}', ['as' => 'profile.single_payment', 'uses' => 'UsersController@singlePayment']);

		Route::get('users/{username}/scorecard/{id}', ['as' => 'profile.learner_scorecard', 'uses' => 'UsersController@learnerScorecard']);
		Route::get('users/{username}/scorecard/{id}/compare', ['as' => 'profile.comparison_scorecard', 'uses' => 'UsersController@compareScorecards']);
	});

	// master judge routes
	Route::group(['before' => 'auth|is_master_judge'], function() {
		Route::get('master', ['as' => 'master.dashboard', 'uses' => 'ScorecardController@listMaster']);
		Route::get('master/scorecard/{id}', ['as' => 'master.scorecard', 'uses' => 'ScorecardController@masterScorecard']);
	});

	// scorecard verification routes
	Route::group(['before' => 'auth|can_verify'], function() {
		Route::get('verify', ['as' => 'verification.dashboard', 'uses' => 'VerificationController@dashboard']);
		Route::get('verify/view/{id}', ['as' => 'verification.single', 'uses' => 'VerificationController@single']);
		Route::get('verify/view/scorecard/{id}', ['as' => 'verification.view_scorecard', 'uses' => 'VerificationController@displayScorecard']);
		Route::post('verify', ['as' => 'verification.save', 'uses' => 'VerificationController@save']);
	});

	// embedded video player
	Route::get('videos/{search}', ['as' => 'videos.player', 'uses' => 'VideosController@videoPlayer']);

	// admin panel routes
	Route::group(['prefix' => 'admin', 'before' => 'auth|is_admin', 'namespace' => 'Admin'], function() {
		Route::get("/", ['as' => 'admin.dashboard', 'uses'  => 'BaseController@dashboard']);
		Route::resource('coupons', 'CouponsController');
		Route::resource('orders', 'OrdersController', ['only' => ['index', 'show', 'destroy']]);
		Route::get('status/inprogress', ['as' => 'admin.status.inprogress', 'uses' => 'StatusController@inprogress' ]);
		Route::get('status/pending', ['as' => 'admin.status.pending', 'uses' => 'StatusController@pending' ]);
		Route::get('status/satisfactory', ['as' => 'admin.status.satisfactory', 'uses' => 'StatusController@satisfactory' ]);
		Route::get('status/unsatisfactory', ['as' => 'admin.status.unsatisfactory', 'uses' => 'StatusController@unsatisfactory' ]);
		Route::get('status/completed', ['as' => 'admin.status.completed', 'uses' => 'StatusController@completed' ]);
		Route::get('status', ['as' => 'admin.status', 'uses' => 'StatusController@inprogress' ]);
		Route::resource('packages', 'PackagesController');
		Route::resource('payments', 'PaymentsController', ['only' => ['index', 'show']]);
		Route::resource('roles', 'RolesController');
		Route::resource('templates', 'TemplatesController');
		Route::get('templates/{id}/rows', ['as' => 'admin.templates.rows', 'uses' => 'TemplatesController@getTemplateRows']);
		Route::post('templates/{id}/rows', ['as' => 'admin.templates.submitRows', 'uses' => 'TemplatesController@submitTemplateRows']);
		Route::resource('users', 'UsersController', ['only' => ['index']]);
	});

	// AJAX routes
	Route::group(['before' => 'ajax'], function() {
		// ADMIN
		Route::post('videos/check', ['before' => 'auth', 'as' => 'videos.check_url', 'uses' => 'VideosController@checkVideo']);
		Route::post('users/search', ['as' => 'users.search', 'uses' => 'UsersController@search']);

		// CHECKOUT
		Route::post('checkout/remove_item', ['before' => 'auth', 'as' => 'order.remove', 'uses' => 'CheckoutController@removeItem']);
		Route::post('checkout/add_coupon', ['before' => 'auth', 'as' => 'coupons.add', 'uses' => 'CheckoutController@addCoupon']);
		Route::post('checkout/remove_coupon', ['before' => 'auth', 'as' => 'coupons.remove', 'uses' => 'CheckoutController@removeCoupon']);

		// SCORECARD
		Route::post('scorecard/save_row', ['before' => 'auth', 'as' => 'scorecard.save_row', 'uses' => 'ScorecardController@saveRow']);
		Route::post('scorecard/save_score', ['before' => 'auth', 'as' => 'scorecard.save_score', 'uses' => 'ScorecardController@saveManualScore']);
		Route::post('scorecard/save_comment', ['before' => 'auth', 'as' => 'scorecard.save_comment', 'uses' => 'ScorecardController@saveGlobalComment']);
		Route::post('scorecard/validate_scorecard', ['before' => 'auth', 'as' => 'scorecard.validate_scorecard', 'uses' => 'ScorecardController@validate']);
		Route::post('scorecard/save_scorecard', ['before' => 'auth', 'as' => 'scorecard.save_scorecard', 'uses' => 'ScorecardController@markComplete']);

		// DRAG AND DROP SCORECARDS
		Route::post('scorecard/save_sorting', ['before' => 'auth', 'as' => 'scorecard.save_sorting', 'uses' => 'ScorecardController@saveSorting']);
		Route::post('scorecard/load_ranked_scorecard', ['before' => 'auth', 'as' => 'scorecard.load_ranked_scorecard', 'uses' => 'ScorecardController@loadRankedScorecard']);
		Route::post('scorecard/save_ranked_comment', ['before' => 'auth', 'as' => 'scorecard.save_ranked_comment', 'uses' => 'ScorecardController@saveRankedComment']);
		Route::post('scorecard/save_ranked_scorecard', ['before' => 'auth', 'as' => 'scorecard.save_ranked_scorecard', 'uses' => 'ScorecardController@markRankedComplete']);

		// SCORECARD VERIFICATION
		Route::post('verify/{id}', ['before' => 'auth|can_verify', 'as' => 'verification.update', 'uses' => 'VerificationController@update']);
		Route::post('verify/{id}/delete', ['before' => 'auth|can_verify', 'as' => 'verification.delete', 'uses' => 'VerificationController@delete']);
		Route::post('verify/{id}/verify', ['before' => 'auth|can_verify', 'as' => 'verification.verify', 'uses' => 'VerificationController@verified']);
		Route::post('verify/{id}/completed', ['as' => 'verification.completed', 'uses' => 'VerificationController@completed' ]);

		// STATUS 
		Route::post('statusajax/inprogress', ['as' => 'statusajax.inprogress', 'uses' => 'StatusController@inprogress' ] );
		Route::post('statusajax/pending', ['as' => 'statusajax.pending', 'uses' => 'StatusController@pending' ] );
		Route::post('statusajax/satisfactory', ['as' => 'statusajax.satisfactory', 'uses' => 'StatusController@satisfactory' ] );
		Route::post('statusajax/unsatisfactory', ['as' => 'statusajax.unsatisfactory', 'uses' => 'StatusController@unsatisfactory' ] );
		Route::post('statusajax/completed', ['as' => 'statusajax.completed', 'uses' => 'StatusController@completed' ] );
		
		// LOCALIZATION
		Route::post('states', ['as' => 'states.get', 'uses' => 'LoginController@getStates']);
	});
});
